### ISSUE TITLE
Does qwik-speak-extract takes into account arrays?

### ISSUE THREAD

**Issue by fprl** [robisim74/qwik-speak#103]
Hi again,

One question, is it possible to make `qwik-speak-extract` to take arrays into account? for example consider this `home.json` file:
```json
{
  "home": {
    "faq": {
      "title": "Frequently Asked Questions",
      "faqs": [
        {"question": "", "answer": ""},
        {"question": "", "answer": ""},
       ],
     }
   }
 }
```
```tsx
// component
const faqs = t<{ question: string; answer: string }[]>('home.faq.faqs')
```

Then I run `"qwik-speak-extract": "qwik-speak-extract --supportedLangs=nl,en,de,fr,it --assetsPath=./src/i18n",`

The JSON gets overwritten and now `home.faq.faqs` is a string.

Thank you

**Comment by robisim74** [comment]
Thanks for reporting. That's a bug.

**Comment by robisim74** [comment]
@fprl Should be fixed in https://github.com/robisim74/qwik-speak/releases/tag/v0.19.0

**Comment by fprl** [comment]
@robisim74 Thanks a lot, It's working now!
