### ISSUE TITLE
Fix failing tests on pipeline

### ISSUE THREAD

**Issue by DevHusariaSolutions** [robisim74/qwik-speak#107]
I know reason behind tests failing.
Most clouds have x64 architecture for most of machines, so we need specific package for "sharp".

For me adding in package.json dependencies list
```
"@img/sharp-linux-x64": "^0.33.1"
```
works great.

**Comment by robisim74** [comment]
@DevHusariaSolutions Are you sure you are in the right repo? If yes, could you explain the issue? Thank you
