### ISSUE TITLE
FYI: DeepL translator for qwik-speak

### ISSUE THREAD

**Issue by genox** [robisim74/qwik-speak#112]
Not really an issue. But maybe you can give this a try and reference it somewhere in the docs if you like it.

I just released an auto-translator that integrates with qwik-speak and DeepL: https://www.npmjs.com/package/@tegonal/qwik-speak-deepl

It automatically gets default language and language targets from the qwikSpeakInline() config. All you need to provide is an api key (free api is fine).

**Comment by robisim74** [comment]
Thanks! I will add it in the _Automatic translation_ section: https://github.com/robisim74/qwik-speak?tab=readme-ov-file#automatic-translation

**Comment by robisim74** [comment]
Added!

**Comment by genox** [comment]
Thank you
