### ISSUE TITLE
Qwik-speak-extract: Maximum call stack exceeded

### ISSUE THREAD

**Issue by genox** [robisim74/qwik-speak#113]
Hi,

Had a bit of downtime and tried to test the new setup. While trying to extract the strings I got the following error on node 20.11.0:

```
Qwik Speak Extract
extracting translation...
file:///....../node_modules/qwik-speak/extract/index.js:14
  const p = (a) => (e = l, { type: a, value: O(), position: { start: e, end: l } }), P = (a) => {
                                                                                         ^

RangeError: Maximum call stack size exceeded

```

This happens both with --autoKeys enabled or disabled.

However, running the `npm run` script in this repository (e.g. checking out this repository here and running the test script) works fine (same node version, etc).

Could be related to the amount of source files that are being parsed? Or a large component that causes a bit too much recursion? That is the only difference I can see right now.

**Comment by robisim74** [comment]
It should not depend on the number or size of files: the parser performs a sequential scan of each function p and t: https://github.com/robisim74/qwik-speak/blob/main/packages/qwik-speak/tools/core/parser.ts#L388

It seems that the tokenizer can't find the end of a function t or p, and goes into stack error.

Without recreating the problem it is difficult for me to understand why it happens, I ask you:
- Do you get the same error with version v0.19?
- Have you added any particularly complex t or p functions, for example on multiple lines, with many options and parentheses?

**Comment by robisim74** [comment]
I was able to recreate the error, for example when the closing quotes are missing: `<h3>{t('params)}</h3>`

In version 0.20.1 I added a log of the t or p function that should generate the error

**Comment by genox** [comment]
👍
