### ISSUE TITLE
If/else - condition

### ISSUE THREAD

**Issue by dejurin** [robisim74/qwik-speak#115]
Hello, firstly, I would like to thank you for your contribution to the development of plugins for Qwik.
I did not find a description of the conditions in the documentation. Is it possible to support conditions?

Something like that
```js
const message = "{isDay, select, true {Day} other {Night}}";
```

**Comment by robisim74** [comment]
I assume you are reporting the feature from some other library/framework.

The syntax you propose does not make any sense relative to the current syntax of this library.

Please provide an example that can be understood by those who don't know what you want, and explain the use case.

**Comment by dejurin** [comment]
I apologize for the bad example. Corrected. I'm interested in the ability to create **if/else conditions** or **selecting enum-based values** in the translation text.

**Comment by robisim74** [comment]
It's not just a question of Intl syntax: I don't think further complicating message texts is a good thing, because they become incomprehensible to translators. While as programmers we can easily handle conditions in jsx.
