### ISSUE TITLE
Sitemap is not generating / finding routes when using localized routing

### ISSUE THREAD

**Issue by kwojtkowiak** [robisim74/qwik-speak#123]
Hello,

I have an issue with generating sitemap.xml (following the official Qwik docs) when I use localized routing with the language as the sitemap is empty (no routes are caught). That is how my routes folder looks like now (it's identical to documentation):
```
src/routes/
│   
└───[...lang]/ index.tsx
        layout.tsx
        plugin.ts
        service-worker.ts
```

relevant part of vite.config.ts:

```
plugins: [
      cloudflarePagesAdapter({
        ssg: {
          include: ['/[...lang]/*'],
          origin: 'https://example.com',
          sitemapOutFile: 'sitemap.xml',
        },
      }),
    ],
```

Localized routing is working and the sitemap included all routes correctly before adding this feature. 
Could you please help on this issue?

**Comment by robisim74** [comment]
Adapters are not managed by this library, but by Qwik.

That said:

> following the official Qwik docs

I can't find your example in the official doc, instead I find:
- https://qwik.dev/docs/deployments/cloudflare-pages/
- https://qwik.dev/docs/guides/static-site-generation/#dynamic-ssg-routes

And in the doc of this library: https://github.com/robisim74/qwik-speak/blob/main/docs/adapters.md#static-site-generation-ssg

So you need:

1. Handle the dynamic lang parameter, adding the values it can take to each page included in SSG, e.g.:

_src/routes/[...lang]/index.tsx_
``` typescript
export const onStaticGenerate: StaticGenerateHandler = () => {
  return {
    params: config.supportedLocales.map(locale => {
      return { lang: locale.lang !== config.defaultLocale.lang ? locale.lang : '.' };
    })
  };
};
```

2. Adapter:

```
    plugins: [
      cloudflarePagesAdapter({
        ssg: {
          include: ['/*'],
          origin: 'https://example.com',
          sitemapOutFile: 'sitemap.xml',
        },
      }),
    ],
```

Greetings
