### ISSUE TITLE
Back button doesn't set the locale of the url

### ISSUE THREAD

**Issue by frederikstonge** [robisim74/qwik-speak#14]
I've made a playground with your package. I copied pretty much everything from your sample app, but I did some changes to always show the locale in the URL, instead of hiding it when it's the default.

https://github.com/frederikstonge/qwik-playground

When I change from English to French, and then I press back, it changes the URL back to English, but the site remains in French.

Either I'm doing something wrong, but onGet in layout.tsx isn't called at all, and I can't use the speak context.

**Comment by frederikstonge** [comment]
I just tried your first option, but same thing happen with this scenario :
open the website, go to blow my mind, then change the language, and go back. Url is en-CA but header is in french.

**Comment by robisim74** [comment]
About the first option: if in the real app the user can change language in every page, you should add in _header.tsx_:

```
useClientEffect$(() => {
    window.onpopstate = (event) => {
      if (event) window.location.reload(); // reload the page on back or forward
    };
  }); 
```

About the third option: it seems work, just the selected item is not updated. Check also what happens in layout.

However this is a temporary logic: from the next version Wwik will also support the locale in the envData, and maybe we can get to something more stable and simple.

**Comment by robisim74** [comment]
No problem. I have already spent a lot of time getting the navigation to work, considering the changes that have been and continue to be in qwik-city.

However, in the example app of this library the first and third options seem to work fine: there must be something in the management of the always localized url (even for the default language) that is wrong in your playground.

**Comment by robisim74** [comment]
See also: https://github.com/BuilderIO/qwik/issues/1490

**Comment by robisim74** [comment]
See https://github.com/BuilderIO/qwik/issues/2378

**Comment by robisim74** [comment]
Because QwikCity can't resolve this issue internally, I've updated the documentation on how to implement `ChangeLocale` to handle page back/forward.
