### ISSUE TITLE
Netlify compatibility

### ISSUE THREAD

**Issue by bovealexandre** [robisim74/qwik-speak#19]
Hi,
I'm having an issue with qwik speak whenever I try to deploy to Netlify 

It's like the whole deploy is broken it doesn't even load images but whenever I remove qwik speak it works

**Comment by robisim74** [comment]
Hi @bovealexandre,

are you loading the translations dynamically also in production? If yes, the problem may be that it can't find the files once it's published. What endpoint are you using in `loadTranslation$`?

**Comment by bovealexandre** [comment]
Here is my loadTranslation$

```
export const loadTranslation$: LoadTranslationFn = $(async (lang: string, asset: string, origin?: string) => {
  let url = '';
  // Absolute urls on server
  if (isServer && origin) {
    url = origin;
  }
  url += `/i18n/${lang}/${asset}.json`;
  const data = await fetch(url);
  return data.json();
});
```

**Comment by robisim74** [comment]
Ok, the example works locally, and certainly on an Express server serving the static files. How are static files handled on Netlify?

**Comment by robisim74** [comment]
@bovealexandre I've just published a sample app that implements this example: https://robisim74.gitbook.io/qwik-speak/library/quick-start

This is the linked repo: https://github.com/robisim74/qwik-speak-edge

I deployed the site first, then I tried the edge function too. It seems to work without problems, and also the translation files load correctly without changing the way static files are served: https://qwik-speak-test.netlify.app/

If your problem persists, please provide more details and steps to reproduce the problem.

Greetings

**Comment by bovealexandre** [comment]
I had an old version of Qwik so it crashed the whole thing. 
thank you right now it doesn't compile the index but I'm going to search why.

**Comment by bovealexandre** [comment]
ok I fixed everything but right now it doesn't load default locale
