### ISSUE TITLE
$plural: support for param interpolation

### ISSUE THREAD

**Issue by robisim74** [robisim74/qwik-speak#32]
Hi @robisim74

I just noticed that `$plural` API doesn't support param interpolation. Is it something missing or I misunderstand the API? I have the json
```
"devs": {
    "one": "{{ value }} software developer {{ name }}",
    "other": "{{ value }} software developers {{ name }}"
  }
```
and when I look at `$plural` API, there is no way to pass value for `name`.

Another small thing is, I think `prefix` param name in `$plural` should be renamed to `key` to be clearer.

_Originally posted by @ahnpnl in https://github.com/robisim74/qwik-speak/discussions/29#discussioncomment-5264790_

**Comment by robisim74** [comment]
Supported in latest release: v0.8.0

Greetings!

**Comment by ahnpnl** [comment]
Thanks! Everything works pretty well. I just came across ICU message format for plural today https://unicode-org.github.io/icu/userguide/format_parse/messages/ and also read Angular plural https://angular.io/api/common/I18nPluralPipe which triggers me a suggestion for improvement: should this lib enforce the message format to follow ICU? IMO ICU is a popular standard should be followed.

**Comment by robisim74** [comment]
This library uses Intl APIs for plurals, numbers etc.: APIs build for the web (not for old systems).

Unicode standards and CLDR data are already in its engine.

With Angular Plural pipe (an other similar old solutions) you have to create the mapping (few, many, =0, =1) by yourself (or with the help of translators): `Intl.PluralRules` already gives you the mapping for each language, with other options (like cardinal or ordinal numbers) and makes it easier to extract translations.
