### ISSUE TITLE
hello need help - Build Failure during Production

### ISSUE THREAD

**Issue by arunbharath91** [robisim74/qwik-speak#34]
![image](https://user-images.githubusercontent.com/17268342/226452546-38a9abdf-5180-4761-b2a8-42465fd1e6d9.png)
iam using qwik speak in dev mode. it is working in local
but when iam doing production build "npm run build" it is throwing error. please help on this

dev mode working screen shot
![image](https://user-images.githubusercontent.com/17268342/226455206-0645c382-dfca-4205-b22a-5245caaf6ad7.png)

**Comment by robisim74** [comment]
It's SSG that's not working. If you want to use SSG, you need to provide a running server that serves the files at the ip requested by your static adapter.

**Comment by arunbharath91** [comment]
#Update 
For People who need to take build with static adaptor for testing purpose. 
Please directly hardcode the URL. and also create necessary support files in your domain.
![image](https://user-images.githubusercontent.com/17268342/226993769-950b7048-1f8c-4ba8-89bd-bd57b11c159a.png)

**Comment by robisim74** [comment]
A better solution with edge functions or SSG is to include the translation files in server bundles. I updated the doc: https://robisim74.gitbook.io/qwik-speak/library/adapters

Any feedback is welcome.

**Comment by arunbharath91** [comment]
Thanks For the Solution

**Comment by robisim74** [comment]
See also the recommendation to move the `loadTranslation$` function in a separate file in the latest version: https://github.com/robisim74/qwik-speak/releases/tag/v0.10.0

I'm closing this issue.
