### ISSUE TITLE
Suggest differences between this library and $localize

### ISSUE THREAD

**Issue by phcoliveira** [robisim74/qwik-speak#38]
Hello there and thanks in advance.

Could you please state in the README (or anywhere else you want) the main reasons why someone would this library instead of $localize?

Thanks!

**Comment by robisim74** [comment]
It's not a race, and everyone is free to choose what is best suited to their needs by comparing the documentation.

Perhaps you will find interesting this [discussion](https://github.com/robisim74/qwik-speak/discussions/8), which originated the use of `$localize` in Qwik and the current functions of this library.

Greetings

**Comment by phcoliveira** [comment]
Thanks for your readiness, @robisim74. Perhaps you had the impression that I was grabbing for "which one is better". But this was not my intention. Given that `$localize` seems to be comprehensive, I wonder why you decided to go on and build this library.
