### ISSUE TITLE
How to use value of another term as parameter value

### ISSUE THREAD

**Issue by mahmoudajawad** [robisim74/qwik-speak#4]
If I have following as my localised terms dictionary:
```js
{
  term: 'Term Value',
  termWithParam: 'Term with {{term}}',
}
```

How can I get `Term with Term Value` out of the two terms defined in terms dictionary? trying the following:
```js
_('termWithParam', {term: _('term')})
```
would result in:
```
Term with [object Promise]
```

**Comment by robisim74** [comment]
Try this:

``
_('termWithParam', { term: `${_('term')}` })
``

note the backtick for including translation as a parameter.

**Comment by mahmoudajawad** [comment]
This definitely works. Thanks.
