### ISSUE TITLE
Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by juanpmarin** [robisim74/qwik-speak#49]
Hi! I'm using qwik-speak with the inline plugin, and I'm getting the following error when building for production:
It only fails with version 0.12.1, and works with previous version

```
computing gzip size (0)...[vite-plugin-qwik-speak-inline] Cannot read properties of undefined (reading 'value')
✓ built in 3.56s
error during build:
TypeError: Cannot read properties of undefined (reading 'value')
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1731)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1686)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1686)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1686)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1686)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1686)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1686)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1907)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1686)
    at $ (/home/juan/Projects/every/node_modules/.pnpm/qwik-speak@0.12.1_@builder.io+qwik@1.0.0/node_modules/qwik-speak/inline/index.cjs:6:1686)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by juzicheng** [comment]
I have same problem:

`
vite v4.1.4 building for production...
✓ 87 modules transformed.
[vite-plugin-qwik-speak-inline] Cannot read properties of undefined (reading 'value')
file: D:/work/wocute/ssr/src/s_c7jsucm5pkq.js
error during build:
TypeError: Cannot read properties of undefined (reading 'value')
    at $ (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1527)
    at $ (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
    at $ (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
    at $ (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
    at $ (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
    at m (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1857)
    at m (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1864)
    at $ (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1694)
    at $ (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
    at $ (D:\work\wocute\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

`

**Comment by robisim74** [comment]
@juanpmarin Thanks for reporting. I need to isolate the problem to fix the bug.

In v0.12.1 I made some changes to `params` parsing: are you using `$translate` function somewhere with some particular parameter, like a call expression:

`t('home.greeting', getGreeting('name'))`

To find out, temporarily remove the function from your code and do `npm run build.client`

@juzicheng From your log it looks like you are using version 0.12.0 (which by the way supports Qwik greater than v1): can you provide some more details on when the error started happening? can you do tests like the one described above?

Thanks!

**Comment by juzicheng** [comment]
> I have same problem:
> 
> ```
> vite v4.1.4 building for production...
> ✓ 87 modules transformed.
> [vite-plugin-qwik-speak-inline] Cannot read properties of undefined (reading 'value')
> file: D:/xxx/ssr/src/s_c7jsucm5pkq.js
> error during build:
> TypeError: Cannot read properties of undefined (reading 'value')
>     at $ (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1527)
>     at $ (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
>     at $ (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
>     at $ (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
>     at $ (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
>     at m (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1857)
>     at m (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1864)
>     at $ (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1694)
>     at $ (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
>     at $ (D:\xxx\ssr\node_modules\.pnpm\registry.npmmirror.com+qwik-speak@0.12.0_@builder.io+qwik@0.104.0\node_modules\qwik-speak\inline\index.cjs:6:1703)
>  ELIFECYCLE  Command failed with exit code 1.
>  ELIFECYCLE  Command failed with exit code 1.
> ```



> @juanpmarin Thanks for reporting. I need to isolate the problem to fix the bug.
> 
> In v0.12.1 I made some changes to `params` parsing: are you using `$translate` function somewhere with some particular parameter, like a call expression:
> 
> `t('home.greeting', getGreeting('name'))`
> 
> To find out, temporarily remove the function from your code and do `npm run build.client`
> 
> @juzicheng From your log it looks like you are using version 0.12.0 (which by the way supports Qwik greater than v1): can you provide some more details on when the error started happening? can you do tests like the one described above?
> 
> Thanks!

Thanks!
But when I update `"qwik-speak": "0.12.1",`,  the problem still exists!

my `package.json`:

```
{
  "name": "xxx",
  "description": "SSR for xxx",
  "engines": {
    "node": ">=15.0.0"
  },
  "private": true,
  "scripts": {
    "build:test": "rimraf dist && rimraf server && qwik build --mode testing",
    "build:staging": "rimraf dist && rimraf server && qwik build --mode staging",
    "build": "rimraf dist && rimraf server && qwik build",
    "deploy": "node server/entry.express",
    "build.client": "vite build",
    "build.preview": "vite build --ssr src/entry.preview.tsx",
    "build.server": "vite build -c adapters/express/vite.config.ts",
    "build.types": "tsc --incremental --noEmit",
    "dev": "vite --mode ssr --port 8888 --host",
    "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
    "fmt": "prettier --write .",
    "fmt.check": "prettier --check .",
    "lint": "eslint \"src/**/*.ts*\"",
    "preview": "qwik build preview && vite preview --open",
    "start": "vite --open --mode ssr --port 8888",
    "qwik": "qwik",
    "rm.dist.server": "rimraf dist && rimraf server"
  },
  "devDependencies": {
    "@builder.io/qwik": "0.104.0",
    "@builder.io/qwik-city": "0.104.0",
    "@types/compression": "^1.7.2",
    "@types/eslint": "8.21.1",
    "@types/express": "4.17.17",
    "@types/node": "^18.14.0",
    "@types/node-fetch": "latest",
    "@typescript-eslint/eslint-plugin": "5.54.0",
    "@typescript-eslint/parser": "5.54.0",
    "compression": "^1.7.4",
    "eslint": "8.10.0",
    "eslint-plugin-qwik": "0.21.0",
    "express": "4.18.2",
    "node-fetch": "3.3.0",
    "prettier": "2.8.4",
    "qwik-speak": "0.12.0",
    "typescript": "4.9.5",
    "undici": "5.20.0",
    "vite": "4.1.4",
    "vite-plugin-compression": "^0.5.1",
    "vite-tsconfig-paths": "3.5.0"
  },
  "dependencies": {
    "qwik-image": "^0.0.3"
  }
}

```

I did use the `$translate` function in a component:

\test\index.tsx :

```
import type { Signal } from "@builder.io/qwik";
import { $, component$, Slot, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import { $translate as t, displayName as dn, Speak, useSpeakConfig } from "qwik-speak";
// import { config } from "@plug/qwikSpeak";
import { useLocale } from "~/hooks/useLocale";


export { head } from "@Html/DocHead";

export const CardSlot = component$(({ title }: { title: string }) => {
    return (
        <article class="message is-danger">
            <div class="message-header">
                <p>{title}</p>
            </div>
            <div class="message-body">
                <Slot />
            </div>
        </article>
    );
});

export const ToggleLocale = component$(() => {
    const config = useSpeakConfig();

    const changeLocale$ = $((lang: any) => {
        location.replace(location.href.replace(/language=([a-zA-Z-]*)/gi, `language=${lang}`));
    });

    return (
        <CardSlot title="Toggle Locale">
            <div class="gap-[0.75rem] is-flex">
                {config.supportedLocales.map(({ lang }, i) => {
                    return (
                        <button
                            class="button is-link is-outlined"
                            key={i}
                            onClick$={async () => {
                                await changeLocale$(lang);
                                // change language
                                // location.replace(location.href.replace(/language=([a-zA-Z-]*)/gi, `language=${lang}`));
                            }}
                        >
                            {lang}: {dn(lang, { type: "language" })}
                        </button>
                    );
                })}
            </div>
        </CardSlot>
    );
});

export const GlobalText = component$(({ fName = "[lang]" }: { fName: string | null }) => {
    return (
        <CardSlot title={`/i18n/${fName}/global.json`}>
            <div>
                app.AppName:{" "}
                <span class="tag is-info">
                    {t("app.AppName@@{{defaultValue}}", {
                        defaultValue: "This is default value!",
                    })}
                </span>
            </div>
            <div>
                app.title:{" "}
                <span class="tag is-info">
                    {t("app.title@@{{defaultValue}}", {
                        str: t("app.AppName"),
                        defaultValue: "Default: Unknown",
                    })}
                </span>
            </div>
        </CardSlot>
    );
});

export const TestText = component$(({ fName = "[lang]" }: { fName: string | null }) => {
    return (
        <CardSlot title={`/i18n/${fName}/test.json`}>
            <div>
                test.testStr: <span class="tag is-info">{t("test.testStr")}</span>
            </div>
        </CardSlot>
    );
});

export const Child = component$(() => {
    const _l: Signal<string | null> = useSignal("");
    useVisibleTask$(() => {
        _l.value = window.localStorage.getItem("language");
    });

    return (
        <div>
            <ToggleLocale />
            <GlobalText fName={_l.value} />
            <TestText fName={_l.value} />
        </div>
    );
});

export default component$(() => {
    useLocale();
    return (
        <Speak assets={["test"]}>
            <Child />
        </Speak>
    );
});

```

in Dev, it working, but no in production!

Can you help me? thx!

**Comment by juzicheng** [comment]
I tried to do this, but it still doesn't working. 
```
$ pnpm i
Packages: +4 -4
++++----
Downloading registry.npmmirror.com/@builder.io/qwik/1.1.1: 12 MB/12 MB, done
Progress: resolved 382, reused 381, downloaded 1, added 1, done

devDependencies:
- @builder.io/qwik
+ @builder.io/qwik 1.1.1
- @builder.io/qwik-city
+ @builder.io/qwik-city 1.1.1
- qwik-speak
+ qwik-speak 0.12.1

```

**Comment by robisim74** [comment]
@juzicheng Yes in dev works, because the Inline plugin works only in prod mode.

I found the issue in you code:

```
{t("app.title@@{{defaultValue}}", {
  str: t("app.AppName"),
  defaultValue: "Default: Unknown",
})}
```

are the colon in the string: "Default: Unknown".

However if you use parameters like this you will have other problems: `$translate` of a parameter: what's the point?

**Comment by juzicheng** [comment]
> 

![image](https://github.com/robisim74/qwik-speak/assets/34231537/85afc1fc-fa6e-4b8c-aeba-658060480fd8)



it's a test demo, just show other developer. don't care it  ! 😂

I have just started using qwik, no long time.I am still trying something, haha. If there are any issues with my writing, please help me correct it. Thank you!

**Comment by juzicheng** [comment]
@robisim74 

When I remove the colon `:`, it can compile normally.

![image](https://github.com/robisim74/qwik-speak/assets/34231537/af10f47e-aa9c-4ef9-9132-53c238183894)

**Comment by robisim74** [comment]
Yes, it compiles: but the colon should be supported in literals!

Then, the `str` parameter is not used in your example, but in production it will not translated, because `$translate` inside a `$translate` is not supported (it will considered a dynamic key).

You have to keep in mind that in production the `$translate` function is only a placeholder: it is replaced with the translated text

**Comment by juzicheng** [comment]
> Yes, it compiles: but the colon should be supported in literals!
> 
> Then, the `str` parameter is not used in your example, but in production it will not translated, because `$translate` inside a `$translate` is not supported (it will considered a dynamic key).
> 
> You have to keep in mind that in production the `$translate` function is only a placeholder: it is replaced with the translated text

ok, thanks, i think i got this.
I'm try it now.

Thank you for your patience!

**Comment by robisim74** [comment]
@juzicheng  I released a new versions that should solve the problem of colon in params. I also added support for parameter stranslation

**Comment by robisim74** [comment]
@juanpmarin Version v0.12.2 contains fixes that maybe solve your problem too.

If not, you should now see the log for the function that is causing the problem in the console.

Please, let me know

**Comment by juanpmarin** [comment]
The latest version fixed my issue, thanks! @robisim74

**Comment by robisim74** [comment]
Okay, glad to know. These issues are useful for fine-tuning the Inline tool.
