### ISSUE TITLE
Runtime assets seem not to work with DocumentHead

### ISSUE THREAD

**Issue by Zankel-Engineering** [robisim74/qwik-speak#55]
Hi Robi,

first I would like to thank you for this great contribution. I was thinking about building a translation library for Qwik myself, but then found yours.

Currently I face the issue that the title and the description of the DocumentHead seems not to be translated. I added the runtime.json to the runtimeAssets in the config, but it stills shows the placeholder.

Do I miss something here?

One side note I always hated about ngx-translate that it is not type-safe. I was thinking about what to add to qwik-speak to make that feasible. I have had an own solution for Angular that uses a distributed-translate-loader-approach. Maybe we could customize the useTranslate hook to give back a function t that expects a dot-seperated string which matches the keys from the json that is used in the current scope. Especially for large projects that might be a better solution. Drawback is that we could only use the default language, but we could implement an unittest that checks wether the structure of the jsons is equal over all languages.

What do you think?

Sebastian

**Comment by robisim74** [comment]
Hi,

about the problem with `DocumentHead`, you can find a detailed step by step in tutorials, and in this repository a working example app: did you update the keys in `DocumentHead `to point your `runtime` file? Try to verify, and if it still doesn't work, please post the relevant code.

About your second question, I'm not sure I understand. Could you open a [discussion ](https://github.com/robisim74/qwik-speak/discussions) describing the problem and how it could be solved?

Thanks!

**Comment by Zankel-Engineering** [comment]
Hi Robi,

thanks for your answer. 

My head looks like this:

```ts
export const head: DocumentHead = {
    title: 'runtime.page.largeCompany.title',
    meta: [
        {
            name: 'description',
            content: 'runtime.page.largeCompany.description'
        }
    ]
};
```

My config looks like this:

import type { SpeakConfig } from 'qwik-speak';

```ts
export const config: SpeakConfig = {
    defaultLocale: {
        lang: 'de-DE',
        currency: 'EUR',
        timeZone: 'Europe/Berlin'
    },
    supportedLocales: [
        { lang: 'de-DE', currency: 'EUR', timeZone: 'Europe/Berlin' },
        { lang: 'en-US', currency: 'USD', timeZone: 'America/Los_Angeles' }
    ],
    assets: [
        'app' // Translations shared by the pages
    ],
    runtimeAssets: [
        'runtime' // Translations with dynamic keys or parameters
    ]
};
```

Do I miss something here? I was looking into your example before. But I was not able to tell if I forgot to add anything.

Thanks
Sebastian

**Comment by robisim74** [comment]
That's correct. Check also [router-head.tsx](https://github.com/robisim74/qwik-speak/blob/main/src/components/router-head/router-head.tsx) and the route property of your  [runtime](https://github.com/robisim74/qwik-speak/blob/main/i18n/en-US/runtime.json) file.

**Comment by Zankel-Engineering** [comment]
He thanks. It worked. I was missing that first part. To my other request. I am also not sure how we could make that work. But the useContext hook also infers the type. We could maybe somehow include the jsons in TypeScript to infer their type only in the dev mode and then use something like this:

https://www.typescriptlang.org/play?#code/C4TwDgpgBACghsAFgZwCoHsDKwBOBLAOwHMYd0xkAeVAGliggA9gICATZKZXQogbQC6UALxRBAPhFRUDZqw5cexAFBQoAfliqoALmmyW7TugBGAKwgBjYNs0BvbWrV8A0lEJQAosxxxrlAGsIEHQAM2k6bnxicQE9VFchJkMFUwtrDVgEFAxsaJIyCmpEuj4AOgqYOhcBST1yyuqBAG5HKABfPm9cP2BA4LCIxXzY7XqW5WVQSCgAKXRCagN5TijeQToAEWWjYd5JYW0ZZJWxIU0CCAA3CBxdI52FPkJQ26gAMXOP+7VjuV3ngRXnd3nQKmUXm8AErnbTvR6rJRETIAAwAJHZ3u0MZtsXZ5otur5-FDIkiJFtxO0UbooJcbncdNo1sRWlNwNAALIgTYQCBgADy5iswCkDjUoXQ6D04qcJjgOBlbTU8oAXnoWURWk4OtrddoAI4AV0YegIRoAtiZbnrEBAADb26VQWVqMgmPAapF69qtX2TabQXn8lzBKQEgiUeBINBYJGkchUbnBwXC6ziOgAIjKmfErSAA

Will leave that open so that you see my answer.

**Comment by robisim74** [comment]
Moved to #56
