### ISSUE TITLE
"isDev" not defined

### ISSUE THREAD

**Issue by NelminDev** [robisim74/qwik-speak#58]
I followed all instructions on the quick start till the end of the page but in the entry.ssr.tsx file I get the error that "isDev" is not defined.

[**_My entry.ssr.tsx file_**](https://hastebin.com/share/husofedoya.javascript)

![image](https://github.com/robisim74/qwik-speak/assets/82663068/cdd2caa3-05b9-4e5e-b6a0-538b57d3269a)

**Comment by robisim74** [comment]
Import:

`import { isDev } from '@builder.io/qwik/build';`
