### ISSUE TITLE
Intercept the request in the lib to get the browser language

### ISSUE THREAD

**Issue by Zankel-Engineering** [robisim74/qwik-speak#59]
Hi Robi,

I saw that internally the useServerData hook is used. I checked the code of Qwik in the node_modules. It is kinda cryptic. But I don't have so much time today to try to clone the Qwik repo and understand what is going on under the hood. So I am not sure what they are doing and if that is a point.

But why we don't use the Accept-Language header to get a grasp of the browser language in a routeLoader? That should also work in development where I always get the lib falling back to the default.

Serverlanguage might not be the correct here.

Just an idea. Don't know if it is valid. I will go to the Gym now and spend a little bit time with my wife :-). Was sitting in front of the computer all day again. But I want to try to get everything out of the framework with the zankel-engineering website. As soon as I am 80% satisfied with it and it is deployable I will make it public so that people even less experienced that Iam can maybe get a couple of ideas from it.

Qwik feels to me a little bit unstructured for enterprise grade applications. Maybe that is also a point where some companies could have a need for consulting in the future. Error reporting is also really bad. But he, it is open source and I am happy and thankful that somebody puts in the time to make something like this available. I never had the feeling that doing much open source as a small freelancer would be worth it. Anyway. Hear you soon.

Sebastian

**Comment by robisim74** [comment]
I think in your project you forgot to add the part that resolves and sets the locale: https://robisim74.gitbook.io/qwik-speak/library/quick-start#resolve-locale

I'm closing, as I don't see any issues here.

**Comment by Zankel-Engineering** [comment]
Okay. My mistake. I have to say I don't yet completly understand the Qwik framework, since I only have time to play around with it a little in the weekends. I was also on your website and saw that you are an independent freelancer, too. If you want send me an email to s.zankel@zankel-engineering.de. I would like to discuss something with you not related to the library, which demands a more private channel.
