### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by vptill** [robisim74/qwik-speak#60]
Hello,

I have finished rewriting my website from Angular to Qwik and I have been using Qwik Speak without any problems until now. 

When building the app for production, I get an error: 

`vite v4.3.3 building for production...
✓ 2672 modules transformed.
computing gzip size (0)...[vite-plugin-qwik-speak-inline] EMFILE: too many open files, open '\dist\build\nl\q-678594ab.js'
✓ built in 10.03s
error during build:
Error: EMFILE: too many open files, open '\dist\build\nl\q-678594ab.js'`

This issue appears if I have too many supported languages set in qwikSpeakInline(). It works well with 4 languages set, but it will fail with 5+. I have a total of 14 supported languages, so this is an issue that must be fixed before I can deploy my app to production.

**Comment by robisim74** [comment]
Should be fixed in v0.14.1. Please let me know

**Comment by vptill** [comment]
Yes, it worked perfectly. Thanks for the quick help
