### ISSUE TITLE
In production build it seems like that the translation is lost on route change.

### ISSUE THREAD

**Issue by Zankel-Engineering** [robisim74/qwik-speak#65]
Hi Robi,

might also be an issue on my side. But I don't know where.

Please see attached screenshot after a route change the translation for a json key is always undefined.

![image](https://github.com/robisim74/qwik-speak/assets/43412711/4ebef5a9-79d8-488a-90ba-f42cb3b64edc)

Do you have an idea. This behaviour only occurs in the prod build.

You can also see it here:

https://1eedbbba.zankel-engineering.pages.dev/

Sebastian

**Comment by robisim74** [comment]
Hi Sebastian,

as you can see from your screenshot, the translation in the js chunks has not been inlined.

This happens when the keys are dynamic, for example: `${type}.cta.primary` because it is not possible to know the parameter value `type` during the build: look at the `qwik-speak-inline.log` file in your root folder after the build.

The dynamic keys must be placed in the `runtimeAssets`, as explained [here](https://robisim74.gitbook.io/qwik-speak/tools/inline#qwik-speak-inline-vite-plugin-and-runtime).

You can also find a step by step guide in Quick start and Localized routing examples.

**Comment by Zankel-Engineering** [comment]
Can you please point me out in the right direction in github what is
exactly the reason for that? I understand the problem, but would like to
see the exact code position where it manifests.

Am Mo., 10. Juli 2023 um 15:13 Uhr schrieb Sebastian Zankel <
***@***.***>:

**Comment by robisim74** [comment]
I'm not sure I understand what I have to tell you. Please can you explain?

**Comment by Zankel-Engineering** [comment]
Morning Robi. Woke up early again today. It is shit hot here in Germany.

I was thinking if it is feasible to use: Hookyns/tst-reflect: Advanced
TypeScript runtime reflection system (github.com)
<https://github.com/Hookyns/tst-reflect> to get the union type values in
the plugin and make using variables possible.

What do you think?

Am Mo., 10. Juli 2023 um 23:00 Uhr schrieb Roberto Simonetti <
***@***.***>:

**Comment by robisim74** [comment]
During the build, `Inline `plugin transform the `t` function into string in js chunks, for example:

From:
```
const t = useTranslate();
const banner = { text: t('home.video.text') };
```

to:
```
const banner = { text: `span class="primary">Welcome!</span><br />Find out now why you are in the right place` };
```
and creates browser chunks one for each language: therefore no runtime lookup, no file loading and better performance.

When you have code like this:

```
const t = useTranslate();
const { type } = useContext(CompanyContext);
return (
        <h1
            class="xs:text-center sm:text-left xs:text-4xl sm:text-5xl/[4rem]"
            dangerouslySetInnerHTML={t(`${type}.heroSection.headline`)}
         />
    )
```
which value should be used during the build to transform`t(`${type}.heroSection.headline`)` into string? and how would _reflection_ be useful?

**Comment by Zankel-Engineering** [comment]
Hi Robi,

hard to say. I guess both possible values of type in my case 'smallCompany'
and 'largeCompany'. If you check their examples: Hookyns/tst-reflect:
Advanced TypeScript runtime reflection system (github.com)
<https://github.com/Hookyns/tst-reflect> it should be feasible to iterate
over the union values in typescript. But you might be correct, since I
don't know the internal implementation of the inline plugin. I fixed it for
my project, but it might be good for making the library better.

What do you think?

Sebastian

Am Di., 11. Juli 2023 um 09:02 Uhr schrieb Roberto Simonetti <
***@***.***>:

**Comment by Zankel-Engineering** [comment]
Hi Robi I try to extend the qwik-ui package today. I wanted to use this lib here: [Link](https://www.npmjs.com/package/ts-reflection)

It could also help with our problem. But it is so fucking old and it is difficult to patch it. I guess I will do the feature for qwik ui without it. There are methods used from typescript that don't exist anymore. Don't want to update that lib.

Maybe we could write something like this one day ourself. But it is to much work for me today.

I wanted to use it in a typeguard, which doesn't make so much sense here anyway. But at least it can be used as a runtime condition:

export function isKeyOfQwikUiAriaAttributes(
  key: string
): key is keyof QwikUiAriaAttributesKebab {
  const ariaAttributeKeys = propertiesOf<QwikUiAriaAttributesKebab>();
  return ariaAttributeKeys.includes(key as keyof QwikUiAriaAttributesKebab);
}

export function isKeyOfAriaAttributes(
  key: string
): key is keyof AriaAttributes {
  const ariaAttributeKeys = propertiesOf<AriaAttributes>();
  return ariaAttributeKeys.includes(key as keyof AriaAttributes);
}

but not for the typing here because of the typecast.

**Comment by robisim74** [comment]
The problem with _inlining_ isn't just a _types_ problem: even if a _union_ type were available for the variable, what would the _inlining_ do? write a switch with all possible values and rewrite all translation functions? Really risky to do, especially on code already translated and transformed by the Qwik Optimizer.

I'm closing this issue, to avoid confusion. Please open a separate discussion for suggestions and ideas.
