### ISSUE TITLE
New runtime assets are not loaded using Speak component when navigating between same route with diff params

### ISSUE THREAD

**Issue by moxival** [robisim74/qwik-speak#73]
Hi, 
I have found something odd happening when going from `/path/with/params/A` to `/path/with/params/B`

Imagine a route with parameters. 
This route uses Speak component in order to load runtimeAssets that depend on the route parameter. 
SPA-navigating to the same route but with different params will not load the new assets.

I believe [this useTask](https://github.com/robisim74/qwik-speak/blob/0789a7aabf2aa4ede3bf7104de8cd33a9c280470/packages/qwik-speak/src/speak-component.tsx#L30C3-L30C11) is not re-executed when the component does not change (not really understanding Qwik internals and what/when a component gets recreated)

Small example:
```typescript
// /src/routes/path/with/params/[param]/index.tsx

export default component$(() => {
  const loc = useLocation();
  const asset = `build-runtime-asset-${loc.params.param}`; // <- if you console log this, you will see it changes on SPA navigation

  return (
    {/* The runtime assets are loaded only the first time */}
    <Speak runtimeAssets={[asset]}>
      <ComponentPage></ComponentPage>
    </Speak>
  )
});
```

**Comment by robisim74** [comment]
There are 3 problems here:

1. `Speak` component does not _track_ `runtimeAsset `property (but I could add that easily)
2. You should wrap your `asset` variable in a signal, or pass it directly to the props: ```<Speak runtimeAssets={[`build-runtime-asset-${loc.params.param}]}>```
3. The last problem would be the child component `ComponentPage`: you should tell Qwik to rerender it: so you should add a `track` to the `param` and do some stuff with it inside the component.

All these operations could significantly reduce performance. In my opinion, there would be at least 2 good alternatives that are much simpler and more performing:
- don't use SPA navigation for this kind of pages
- or create only one runtime json for this page, nested by the value of `param`:

```
{
  "runtimePage": {
    "1": {
      "dynamic": "I'm a dynamic value - param 1"
    },
    "2": {
      "dynamic": "I'm a dynamic value - param 2"
    }
  }
}
```

and in `ComponentPage`:

```<p>{t(`runtimePage.${loc.params.param}.dynamic`)}</p>```

**Comment by moxival** [comment]
Hey thanks for the fast reply, I actually did try to use signal and to compose the asset name directly at the edge (`Speak runtimeAssets={[build-runtime-asset-${loc.params.param}]}>`), neither of those worked.

I am not tracking the param in the child component at the moment but I fail to see how this will make the Speak component rerun the task (as I said I am relatively confused about what and when gets re-run in Qwik at the moment).

I can use a single runtime json and will end up doing that probably if there is no other way. 
I was just surprised that the runtime was not getting loaded even tho it was changing in the default  component.

Thanks again for your reply.

**Comment by robisim74** [comment]
Please, read carefully the comment above: I have listed 3 problems: the first one I should solve inside the library (this would re-load the new asset)

Then, without _track_ and use the `param` also in your child component, it would never be rendered, because Qwik re-renders the components in isolation, and not the entire subtree of the parent component.
