### ISSUE TITLE
Display [object Object] when I pass it an anchor as a parameter

### ISSUE THREAD

**Issue by sebacc92** [robisim74/qwik-speak#76]
Hello!

I am using this code in my app

`{t('app.hello@@Hello, visit my website {{link}}', { link: <a href="https://google.com/">Google</a> })}`

but that translate this:

'Hello, visit my website [object Object]'

What am I doing wrong? What is the correct way?

Thanks

**Comment by robisim74** [comment]
You can't pass an Html element directly to the `link` param, you have to use quotes:

`<p dangerouslySetInnerHTML={t('app.hello@@Hello, visit my website {{link}}', { link: '<a href="https://google.com/">Google</a>' })}></p>`
