### ISSUE TITLE
For the qwik project deployed by ssg, switching to other languages does not take effect

### ISSUE THREAD

**Issue by AllenIverson1122** [robisim74/qwik-speak#77]
For the qwik project deployed by ssg, switching to other languages does not take effect

**Comment by robisim74** [comment]
In a localized app, SSG must be able to create an index file (pre-rendered) for each page and _for each supported language_.

How are you handling localization in your app?

Without a param for the language in your router, you will only get your default language pre-rendered.

If you are using a localized router, you need to manage a dynamic router, as explained in Qwik docs: https://qwik.builder.io/docs/guides/static-site-generation/#dynamic-ssg-routes

See also https://github.com/robisim74/qwik-speak/issues/71#issuecomment-1661703913

**Comment by robisim74** [comment]
Doc is updated: https://robisim74.gitbook.io/qwik-speak/library/adapters#static-site-generation-ssg
