### ISSUE TITLE
how can i update the runtime asset

### ISSUE THREAD

**Issue by Rainnut** [robisim74/qwik-speak#78]
all tranlate data are runtime asset 
i want update the data for runtime json when the  locale json has changed

I can now update the json when restarting the service, but I expect that no restart is required

**Comment by robisim74** [comment]
_all tranlate data are runtime asset_

This library complies with [i18n](https://qwik.builder.io/docs/integrations/i18n/) expected by Qwik. The `runtimeAssets` have been added to allow you to handle specific cases where it is not possible to know the translation key at compile time (meta tags, values returned from a server, etc.) and not to build the entire app. 

Then your issue lacks all relevant information. Please provide the use case, and an example or detailed description of what you are trying to do or want to achieve.

Thanks

**Comment by robisim74** [comment]
Closing due to lack of information.

**Comment by ThuKieuIC2** [comment]
I think that this use-case is similar to backend-call updated translation data to insert into json then call translation interactive webapps.
For SEO, marketing websites, current Qwik-Speak covers well cases.
