### ISSUE TITLE
Localized routing with optional lang param not working from Qwik v.1.2.8

### ISSUE THREAD

**Issue by robisim74** [robisim74/qwik-speak#83]
Please refer to this issue: https://github.com/BuilderIO/qwik/issues/5049

**Comment by ThuKieuIC2** [comment]
I checked Qwik-Speak 0.15.3 with Qwik 1.2.10 and it now runs well on my machine.

**Comment by robisim74** [comment]
@ThuKieuIC2 `qwik-speak` is not used to generate the localized router, but only Qwik City. 

The fix was done in Qwik, but it hasn't been released yet. Maybe it works for you because you have a single page?

**Comment by ThuKieuIC2** [comment]
I have a multi-page website. It works for static MD/MDX generated HTML but it bugs for other tsx files.
I faced this from the day asking you about MD/MDX and confused to think due to your Speak. 
Sorry!

Okay, just way the new Qwik City.

**Comment by samyung0** [comment]
Maybe throw a redirect to the default locale when there isnt a locale specified in the pathname?

**Comment by ThuKieuIC2** [comment]
@samyung0 Speak is ready to redirect to the default locale. You can see the console log.
But the Qwik update affects some deployed-production.
We also cancel some other projects due to this Qwik way, back to Vite React is still the best.

**Comment by robisim74** [comment]
It should be fixed in the latest Qwik release: v.1.2.11

**Comment by ThuKieuIC2** [comment]
it seems not work with SSG config, all pages routed to 404.

**Comment by ThuKieuIC2** [comment]
@robisim74 Yes. I config SSG for all pages from your tutorial. The build commnand (pnpm build) export all localed SSG files but when run it all shows 404 page.
I changed back to 1.2.6 version and it runs well again.

**Comment by robisim74** [comment]
@ThuKieuIC2 Thanks for the invitation, I'll try to take a look at it later, but the behavior of routing and adapters like SSG don't depend on this library.

**Comment by robisim74** [comment]
@ThuKieuIC2 In your app there is still too much confusion, with too many things started and not finished (even the use of this library). There are links that don't work at all (like terms and privacy, even with previous versions and in dev mode).

However, I believe that your problem arises from the `404.tsx` file located in `[...lang]`: try removing it.

Sorry but I don't have time to go in depth into applications that are still in early development.
