### ISSUE TITLE
[Feature Request] Localized routing with dynamic URL rewriting

### ISSUE THREAD

**Issue by nelsonprsousa** [robisim74/qwik-speak#94]
# Scenario
Currently, it is possible to localize routing with the static URL rewriting feature (`en`->`pt`):
`/home` -> `/inicio`
`/about-us` -> `/sobre-nos`

However, we would like to localize dynamic routing, with slugs. Example (`en`->`pt`):
`/vacations/[countryName]/packages` -> `/ferias/[countryName]/pacotes`

Attempt:
![image](https://github.com/robisim74/qwik-speak/assets/8364345/7743ca5a-ed2f-46d6-af3b-f32b41f49a09)

```typescript
export const rewriteRoutes = [
  {
    prefix: 'pt',
    paths: {
      'vacations/[countryName]/packages': 'ferias/[countryName]/pacotes',
      // other paths
    }
  }
]
```

# Request
Is it possible to have localized routing with dynamic URL rewriting? This should help with SEO on multiple scenarios.

Available to help and even submit a PR, after receiving feedback regarding this feature request (and some guidance would help 🙏 )

Thank you!

**Comment by robisim74** [comment]
Hi Nelson,

when translating paths in `rewriteRoutes `, you must use path segments:

```tsx
export const rewriteRoutes = [
  {
    prefix: 'pt',
    paths: {
      'vacations': 'ferias',
      'packages': 'pacotes'
      // other paths
    }
  }
]
```

Then _slugs_ should work out of the box: https://qwik.builder.io/docs/routing/#rewrite-routes

Example: https://qwik-speak.pages.dev/page/123/

**Comment by nelsonprsousa** [comment]
Indeed, I thought we had to integrate somehow with this lib. Awesome, thanks for your help. 🙏
