### ISSUE TITLE
[Feature request] Domain-based routing

### ISSUE THREAD

**Issue by fprl** [robisim74/qwik-speak#99]
Hi there, 

Thank you for your work, this library is amazing.

I was wondering if Domain-based routing is something you are interested in support.

[Example](https://next-intl-docs.vercel.app/docs/routing/middleware#domain-based-routing).

Thank you.

**Comment by robisim74** [comment]
Hi,

at the moment this library provides only two helper methods, useful for the localization of the path:

- `localizePath `(to add lang prefix in paths)
- `translatePath `(to add lang prefix in paths and translate segments)

Implementing domain management is not difficult: just create a helper method that returns the domain based on the language. And resolve the locale in the `plugin.ts` file based on the domain.

In any case, we could add the support in the library:
- in `SpeakLocale`  we could add the default domain for the language
- `localizePath` and `translatePath` may return the URL with the new domain (when changing language)

I have two doubts:
- keep don't keep prefix (make it optional?)
- in `localizedPath` I could make the prefix optional, but `translatePath` relies on Qwik's rewrite routes, and I don't know if that's possible @claudioshiver

Then in dev mode I think it should use prefixing.

Opinions?

**Comment by fprl** [comment]
Thanks for taking the time to answer me,

> Implementing domain management is not difficult: just create a helper method that returns the domain based on the language. And resolve the locale in the plugin.ts file based on the domain.

Agree here, the library gives you everything you need to solve this.

> I have two doubts:
keep don't keep prefix (make it optional?)
in localizedPath I could make the prefix optional, but translatePath relies on Qwik's rewrite routes, and I don't know if that's possible @claudioshiver

- Maybe I didn't understand this but — following with the idea of default domain — if you have `defaultDomain` and `supportedDomains` properties in the speak-config, it may be a good idea to remove the prefix if `supportedDomains.length > 1`?

Other thing that comes to my mind is that if you declare routes without prefix, devs will need to handle redirects if language doesn't match. For example:
```js
// default domain: english.com
// supported domains: spanish.es | dutch.nl

  {
    prefix: '',
    paths: {
      'huis-ibiza': 'villa-ibiza'
      'huis-ibiza': 'villa-ibiza'
    }
  },
```

If a user goes to dutch.nl/villa-ibiza it will probably work, right? I guess you can create a catchAll route and use `localizePath` and `translatePath` to see if route exists and redirect/404?

**Comment by robisim74** [comment]
> If a user goes to dutch.nl/villa-ibiza it will probably work, right?

Yes, it should work, but we would lose the mapping with the language to know which URLs are valid (I'll have to do some testing, maybe we could handle it by using an optional `lang` parameter in the rewrite routes instead of `prefix`)

So, let's imagine the expected behavior for both methods (`localizePath` and `translatePath`):

**- Dev mode (prefix = true)**

```
http://localhost:5173/
http://localhost:5173/it
http://localhost:5173/page
http://localhost:5173/it/page or http://localhost:5173/it/pagina
```

**- Prod mode (optional prefix = true)**
_(it's ugly in my opinion, but it might be the only way for those who want to use SSG too)_
```
https://example.com/
https://example.it/it
https://example.com/page
https://example.it/it/page or https://example.it/it/pagina
```

**- Prod mode (optional prefix = false)**
```
https://example.com/
https://example.it/
https://example.com/page
https://example.it/page or https://example.it/pagina
```
If a lang have no domain, we could use _default domain with prefix_:
```
https://example.com/de
https://example.com/de/page or https://example.com/de/seite
```

I was thinking of a configuration like this:
```
export const config: SpeakConfig = {
  defaultLocale: { domain: 'example.com' lang: 'en' },
  supportedLocales: [
    { domain: 'example.com', lang: 'en' },
    { domain: 'example.it', lang: 'it'  },
    { lang: 'de' }
  ],
  assets: [
    'app'
  ],
  runtimeAssets: [
    'runtime'
  ]
};
```

What do you think?

**Comment by fprl** [comment]
> Yes, it should work, but we would lose the mapping with the language to know which URLs are valid (I'll have to do some testing, maybe we could handle it by using an optional lang parameter in the rewrite routes instead of prefix)
Yes, this was what I was trying to say haha.

Imo:
### - Dev mode (prefix = true) 
Perfect!

#### - Prod mode (optional prefix = true)
If this would be my choice I will go with a SSR only feature, [same as the Astro team](https://github.com/withastro/astro/pull/9112#discussion_r1395949426).

Why? You can solve this in many different ways:
- Multiple Builds for Different Domains/Languages.
- Using redirects and rewrites (though it could get messy).
- Path-Based routing (what you wrote).
- Middlewares provided by hosting platform (vercel, netlify, cloudflare, etc)

#### - Prod mode (optional prefix = false)
Perfect!

> I was thinking of a configuration like this:
The config file looks perfect and really close to what you have today.

Thanks

**Comment by robisim74** [comment]
Hi @fprl,

the feature is available in the latest release: https://github.com/robisim74/qwik-speak/releases/tag/v0.18.0

Let me know.

**Comment by robisim74** [comment]
As in the code you posted, in `vite.config.ts` you have to import `toPrefixAsNeeded` from `'qwik-speak/inline'`

**Comment by robisim74** [comment]
Then in the `rewriteRoutes` you have to provide `prefix` (as per docs): it will be removed from the `toPrefixAsNeeded` method in production

**Comment by fprl** [comment]
Good catch. Though I just updated everything and have the same issue:

### vite.config.ts
```ts
import { defineConfig } from "vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import { qwikCity } from "@builder.io/qwik-city/vite";
import { qwikSpeakInline, toPrefixAsNeeded } from 'qwik-speak/inline';
import tsconfigPaths from "vite-tsconfig-paths";

import { rewriteRoutes } from "./src/i18n/speak-routes";

export default defineConfig(({ mode }) => {
  return {
    plugins: [
      qwikCity({ rewriteRoutes: toPrefixAsNeeded(rewriteRoutes, mode), trailingSlash: false }),
      qwikVite(),
      qwikSpeakInline({
        defaultLang: 'nl',
        supportedLangs: ['nl', 'en', 'de', 'fr', 'it'],
        assetsPath: './src/i18n'
      }),
      tsconfigPaths(),
    ],
});
```

### speak-config.ts
```ts
import { type SpeakConfig, toPrefixAsNeeded } from 'qwik-speak';

import { rewriteRoutes } from './speak-routes';

export const config: SpeakConfig = {
  rewriteRoutes: toPrefixAsNeeded(rewriteRoutes),
  defaultLocale: { lang: "nl", currency: "EUR", timeZone: "Europe/Amsterdam" },
  supportedLocales: [
    { lang: "nl", currency: "EUR", timeZone: "Europe/Amsterdam" },
    { lang: "en", currency: "GBP", timeZone: "Europe/London" },
    { lang: "de", currency: "EUR", timeZone: "Europe/Berlin" },
    { lang: "fr", currency: "EUR", timeZone: "Europe/Paris" },
    { lang: 'it', currency: 'EUR', timeZone: 'Europe/Rome' },
    // { lang: 'en-US', currency: 'USD', timeZone: 'America/Los_Angeles' }
  ],
  domainBasedRouting: { prefix: 'as-needed' },
};
```

### speak-routes.ts
```ts
import type { RewriteRouteOption } from 'qwik-speak';

import { domains } from './speak-config';

// Translation paths
export const rewriteRoutes: RewriteRouteOption[] = [
  { domain: domains.nl, prefix: '', paths: { 'huis-ibiza': 'huis-ibiza' } },
  { domain: domains.en, prefix: 'en', paths: { 'huis-ibiza': 'villa-ibiza' } },
  { domain: domains.de, prefix: 'de', paths: { 'huis-ibiza': 'villa-ibiza' } },
  { domain: domains.fr, prefix: 'fr', paths: { 'huis-ibiza': 'villa-ibiza' } },
  { domain: domains.it, prefix: 'it', paths: { 'huis-ibiza': 'villa-ibiza' } },
]
```

### plugin.ts
Plugin.ts is a copy of the docs file.

**Comment by robisim74** [comment]
Ok, now the config if correct.

Uhm... the function is this: https://github.com/robisim74/qwik-speak/blob/main/packages/qwik-speak/tools/core/routing.ts

`TypeError: Cannot read properties of undefined (reading 'map')` would appear to be due to the fact that the `rewriteRoutes` you are passing are undefined

**Comment by robisim74** [comment]
`import { domains } from './speak-config';` it seems a circular dependecies: move them in `speak-routes.ts` and check the position of `import { rewriteRoutes } from "./src/i18n/speak-routes";`

**Comment by fprl** [comment]
The circular dependency was the issue, thank you so much. Its amazing how you think about all the routing cases.

**Comment by robisim74** [comment]
The problem is related to Qwik City and to the fact that the routing is file-based: therefore it finds multiple paths pointing to the same file.

Unfortunately it's a behavior I can't fix from this library.

**Comment by fprl** [comment]
Yes, I was sure it was that, Astro works the same way. Thank you again for pushing this :)

**Comment by fprl** [comment]
> The problem is related to Qwik City and to the fact that the routing is file-based: therefore it finds multiple paths pointing to the same file.
> 
> Unfortunately it's a behavior I can't fix from this library.

Hi Roberto, I'm wondering if the last version of qwik/qwik-city with this commit fix this issue? https://github.com/QwikDev/qwik/issues/6375

Regards
